### PR TITLE
UAR-973 UAR-1197 added validation check to fail validation if the Uni…

### PR DESCRIPTION
**Pull request by adamkost**
…tAdministratorType does not allow multiple Unit Admins

### CODE REVIEW

**Comment by adamkost** [comment]
There is, but then all the validation would be done in a single method, and the method would be quite large. The code was written this way to keep the code readable and follow the Kuali coding standards.

**Comment by adamkost** [comment]
Correction: We're getting pieces from 2 different places in the database, so there has to be 2 calls to BOService.

**Comment by nataliac06** [comment]
How about collecting all the UnitTypeCodes and corresponding UnitNumbers that have multipleFlag = false in one Map and do just one call to the BOService at the end and fail the validation if the result is not empty?

**Comment by adamkost** [comment]
While this would work, it would eventually be FAR more memory intensive. Currently on DMO there are only 4 applicable records, but as the system is in use, there could eventually be those 5 types for each of (currently) 627 units. This would be a significant amount of data to pull from the database each time this validation is run.

**Comment by nataliac06** [comment]
Adam, you're still pulling the same information, but instead of pulling it in more calls, you're making just one call to the BO. We can talk about this on HipChat.

**Comment by nataliac06** [comment]
Another suggestion is that we don't actually need the data retrieved by the BOService for validation, but we can try using BOService.countMatching(..) > 0 as a criteria to determine if there are any Unit Administrator for the given Unit and Type.

**Pull request merged**
